import { useState } from "react";
import Loader from "../components/Loader";
import axios from "axios";

export default function Index() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async () => {
    if (!question.trim()) return;
    try {
      setIsLoading(true);
      setAnswer("");
      const response = await axios.post("http://localhost:3000/ask", {
        question,
      });
      const trimmedResponse = response.data.res.answer
        .toString()
        .replaceAll("*", "")
        .replace("answer", "");
      setAnswer(trimmedResponse);
    } catch (error) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <header className="border-b border-white/10">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="text-primary text-3xl">⚖️</div>
            <h1 className="text-4xl font-bold tracking-tight">
              Legal <span className="text-blue-400">AI</span> Assistant
            </h1>
          </div>

          <p className="text-gray-400 text-lg max-w-2xl">
            Advanced legal research powered by Retrieval Augmented Generation
          </p>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <div className="p-8 bg-gray-900/60 border border-white/10 shadow-xl rounded-xl mb-8 backdrop-blur">
          <div className="flex items-start gap-3 mb-4">
            <div className="text-primary text-2xl mt-1">📄</div>

            <div className="flex-1">
              <h2 className="text-2xl font-bold mb-2">
                Ask Your Legal Question
              </h2>
              <p className="text-gray-400 mb-6">
                Provide detailed context for the most accurate response
              </p>

              <textarea
                name="question"
                placeholder="Example: What are the requirements for forming a valid contract under common law?"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                className="w-full min-h-[180px] bg-gray-800 border border-white/10 rounded-lg p-4 focus:outline-none focus:border-blue-400 transition-colors resize-none text-base"
              />
            </div>
          </div>

          <div className="flex justify-end mt-6 ">
            <button
              onClick={handleSubmit}
              disabled={!question.trim() || isLoading}
              className={` ${
                isLoading ? "cursor-not-allowed" : "cursor-pointer"
              } bg-blue-600 hover:bg-blue-500 disabled:bg-gray-600 px-8 py-3 rounded-lg font-semibold flex items-center gap-2 transition-transform hover:scale-105 disabled:scale-100`}
            >
              {isLoading ? "⏳ Processing..." : "Get Answer →"}
            </button>
          </div>
        </div>

        {answer && (
          <div className="p-8 bg-gray-900/70 border border-white/10 shadow-xl rounded-xl animate-fadeIn">
            <div className="flex items-start gap-3 mb-4">
              <div className="text-blue-400 text-2xl mt-1">✨</div>

              <div className="flex-1">
                <h2 className="text-2xl font-bold mb-2">
                  AI-Generated Response
                </h2>
                <p className="text-gray-400 mb-6">
                  Based on legal precedents and statutory analysis
                </p>

                <div className="whitespace-pre-line leading-relaxed text-base text-gray-200">
                  {answer}
                </div>

                <div className="mt-6 pt-6 border-t border-white/10">
                  <p className="text-sm text-gray-400 italic">
                    ⚖️ Disclaimer: This response is generated by AI for
                    informational purposes only. Always consult with a qualified
                    attorney for legal advice.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
        {isLoading && <Loader />}
        {!answer && !isLoading && (
          <div className="grid md:grid-cols-3 gap-6 mt-12">
            <div className="p-6 bg-gray-900/40 border border-white/10 rounded-xl backdrop-blur hover:bg-gray-900/60 transition">
              <div className="text-blue-400 text-3xl mb-3">⚖️</div>
              <h3 className="font-semibold mb-2">Legal Accuracy</h3>
              <p className="text-sm text-gray-400">
                Responses based on verified legal sources and precedents
              </p>
            </div>

            <div className="p-6 bg-gray-900/40 border border-white/10 rounded-xl backdrop-blur hover:bg-gray-900/60 transition">
              <div className="text-blue-400 text-3xl mb-3">✨</div>
              <h3 className="font-semibold mb-2">RAG Technology</h3>
              <p className="text-sm text-gray-400">
                Advanced retrieval system for contextual legal research
              </p>
            </div>

            <div className="p-6 bg-gray-900/40 border border-white/10 rounded-xl backdrop-blur hover:bg-gray-900/60 transition">
              <div className="text-blue-400 text-3xl mb-3">📘</div>
              <h3 className="font-semibold mb-2">Comprehensive</h3>
              <p className="text-sm text-gray-400">
                Detailed analysis covering statutes, case law, and practical
                implications
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
